### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by LejayChen** [jcoupon/venice#2]
Hi,

When installing venice, I have 16 warnings (using gcc compiler)

![PastedGraphic-7](https://user-images.githubusercontent.com/12882788/89057280-bfa0ca00-d333-11ea-8044-1e1dbaf63f03.png)

After finishing installing despite the warnings, I have this problem when trying to run venice:
![PastedGraphic-8](https://user-images.githubusercontent.com/12882788/89057381-e959f100-d333-11ea-88f2-b7fa9edaffb3.png)

How do I fix this?
Thanks!

**Comment by jcoupon** [comment]
Hello ! You must install the CFITSIO library (https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/node3.html) and edit the makefile if necessary. 

Warnings aren't a problem.

**Comment by LejayChen** [comment]
Hi Jean,

I think I fixed it by installing cfitsio though homebrew for MacOS, it seems that the default "./configure & make & make install" does not install the libraries at directories that venice installer is looking at.
